# Generated by Django 5.2.7 on 2025-11-22 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gameroom_gameplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='ladders_map',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='snakes_map',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
