# Generated by Django 5.2.7 on 2025-11-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_gameroom_ladders_map_gameroom_snakes_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='log_rounds',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='round_number',
            field=models.IntegerField(default=1),
        ),
    ]
